/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/console/dependency-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dependency assets */
        get: operations["console-list-dependency-assets"];
        /** Update dependency assets */
        put: operations["console-update-dependency-assets"];
        /** Create dependency assets */
        post: operations["console-create-dependency-assets"];
        /** Delete dependency assets */
        delete: operations["console-delete-dependency-assets"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/github/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin GitHub connection */
        post: operations["console-begin-github-connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitHub installations */
        get: operations["console-list-github-installations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/github/installations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync GitHub installations */
        post: operations["console-sync-github-installations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List GitHub repositories */
        get: operations["console-list-github-repositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/github/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get GitHub status */
        get: operations["console-get-github-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts */
        get: operations["console-list-hosts"];
        /** Update hosts */
        put: operations["console-update-hosts"];
        /** Create hosts */
        post: operations["console-create-hosts"];
        /** Delete hosts */
        delete: operations["console-delete-hosts"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/port-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List port groups */
        get: operations["console-list-port-groups"];
        /** Update port groups */
        put: operations["console-update-port-groups"];
        /** Create port groups */
        post: operations["console-create-port-groups"];
        /** Delete port groups */
        delete: operations["console-delete-port-groups"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/port-groups/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export port groups */
        get: operations["console-export-port-groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/console/service-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List service groups */
        get: operations["console-list-service-groups"];
        /** Update service groups */
        put: operations["console-update-service-groups"];
        /** Create service groups */
        post: operations["console-create-service-groups"];
        /** Delete service groups */
        delete: operations["console-delete-service-groups"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service health */
        get: operations["get-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete GitHub connection */
        get: operations["complete-github-connection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive GitHub webhook */
        post: operations["receive-github-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service metadata */
        get: operations["get-meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ActionDTO.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        BatchIDsDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/BatchIDsDTO.json
             */
            readonly $schema?: string;
            ids: string[];
        };
        DependencyAssetBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/DependencyAssetBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DependencyAssetDTO"][];
        };
        DependencyAssetCreateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/DependencyAssetCreateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DependencyAssetCreateDTO"][];
        };
        DependencyAssetCreateDTO: {
            assetKind?: string;
            assetType?: string;
            controllability?: string;
            description?: string;
            externalId?: string;
            fullName?: string;
            metadata?: string;
            name: string;
            notes?: string;
            provider?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            url?: string;
            visibility?: string;
        };
        DependencyAssetDTO: {
            assetKind: string;
            assetType: string;
            controllability: string;
            /** Format: date-time */
            createdAt: string;
            description: string;
            externalId: string;
            fullName: string;
            id: string;
            /** Format: date-time */
            lastSyncedAt?: string;
            metadata: string;
            name: string;
            notes: string;
            provider: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            updatedAt: string;
            url: string;
            visibility: string;
        };
        DependencyAssetListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/DependencyAssetListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DependencyAssetDTO"][];
        };
        DependencyAssetUpdateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/DependencyAssetUpdateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DependencyAssetUpdateDTO"][];
        };
        DependencyAssetUpdateDTO: {
            assetKind: string;
            assetType: string;
            controllability: string;
            description: string;
            externalId: string;
            fullName: string;
            id: string;
            metadata: string;
            name: string;
            notes: string;
            provider: string;
            /** @enum {string} */
            status: "active" | "disabled";
            url: string;
            visibility: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GithubConnectionStartDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/GithubConnectionStartDTO.json
             */
            readonly $schema?: string;
            /** Format: uri */
            url: string;
        };
        GithubInstallationBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/GithubInstallationBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["GithubInstallationDTO"][];
        };
        GithubInstallationDTO: {
            /** Format: int64 */
            accountId: number;
            accountLogin: string;
            accountType: string;
            /** Format: uri */
            avatarUrl: string;
            /** Format: int64 */
            githubInstallationId: number;
            id: string;
            lastSyncError?: string;
            /** Format: date-time */
            lastSyncedAt?: string;
            /** @enum {string} */
            repositorySelection: "all" | "selected";
            status: string;
            /** Format: date-time */
            suspendedAt?: string;
        };
        GithubInstallationListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/GithubInstallationListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["GithubInstallationDTO"][];
        };
        GithubRepositoryDTO: {
            archived: boolean;
            defaultBranch: string;
            description: string;
            disabled: boolean;
            fork: boolean;
            fullName: string;
            /** Format: int64 */
            githubRepositoryId: number;
            /** Format: uri */
            htmlUrl: string;
            id: string;
            installationId: string;
            /** Format: date-time */
            lastSeenAt: string;
            name: string;
            ownerLogin: string;
            private: boolean;
            /** Format: date-time */
            pushedAt?: string;
            /** Format: date-time */
            remoteUpdatedAt?: string;
            state: string;
            visibility: string;
        };
        GithubRepositoryListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/GithubRepositoryListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["GithubRepositoryDTO"][];
        };
        GithubStatusDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/GithubStatusDTO.json
             */
            readonly $schema?: string;
            appSlug: string;
            enabled: boolean;
            installUrl: string;
        };
        HealthDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/HealthDTO.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
            /**
             * Format: date-time
             * @example 2026-06-15T12:00:00Z
             */
            timestamp: string;
            /** @example 0.1.0 */
            version: string;
        };
        HostBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/HostBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["HostDTO"][];
        };
        HostCreateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/HostCreateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["HostCreateDTO"][];
        };
        HostCreateDTO: {
            ip?: string;
            name: string;
            notes?: string;
            spec?: string;
            /** @enum {string} */
            status?: "active" | "stopped";
        };
        HostDTO: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            ip: string;
            name: string;
            notes: string;
            spec: string;
            /** @enum {string} */
            status: "active" | "stopped";
            /** Format: date-time */
            updatedAt: string;
        };
        HostListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/HostListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["HostDTO"][];
        };
        HostUpdateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/HostUpdateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["HostUpdateDTO"][];
        };
        HostUpdateDTO: {
            id: string;
            ip: string;
            name: string;
            notes: string;
            spec: string;
            /** @enum {string} */
            status: "active" | "stopped";
        };
        MetaDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/MetaDTO.json
             */
            readonly $schema?: string;
            /** @example /api */
            docsPath: string;
            /** @example Miniport */
            name: string;
            /** @example 0.1.0 */
            version: string;
        };
        PortGroupAssetLinkDTO: {
            asset?: components["schemas"]["DependencyAssetDTO"];
            assetId: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            notes: string;
            portGroupId: string;
            portSlotId: string;
            relationType: string;
            required: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        PortGroupAssetLinkInputDTO: {
            assetId?: string;
            id?: string;
            notes?: string;
            portSlotId?: string;
            relationType?: string;
            required?: boolean;
        };
        PortGroupBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/PortGroupBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["PortGroupDTO"][];
        };
        PortGroupCreateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/PortGroupCreateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["PortGroupCreateDTO"][];
        };
        PortGroupCreateDTO: {
            assetLinks?: components["schemas"]["PortGroupAssetLinkInputDTO"][];
            environmentName?: string;
            environmentOwner?: string;
            hostId?: string;
            notes?: string;
            /** Format: int64 */
            portPrefix?: number;
            repositoryLinks?: components["schemas"]["PortGroupRepositoryLinkInputDTO"][];
            /** @enum {string} */
            runtimeMode?: "dind" | "host";
            runtimeName?: string;
            serviceIp?: string;
            slots?: components["schemas"]["PortSlotInputDTO"][];
            status?: string;
            tags?: string;
        };
        PortGroupDTO: {
            assetLinks: components["schemas"]["PortGroupAssetLinkDTO"][];
            /** Format: date-time */
            createdAt: string;
            environmentName: string;
            environmentOwner: string;
            host?: components["schemas"]["HostDTO"];
            hostId: string;
            id: string;
            notes: string;
            /** Format: int64 */
            portPrefix: number;
            repositoryLinks: components["schemas"]["PortGroupRepositoryLinkDTO"][];
            /** @enum {string} */
            runtimeMode: "dind" | "host";
            runtimeName: string;
            serviceIp: string;
            slots: components["schemas"]["PortSlotDTO"][];
            status: string;
            tags: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PortGroupListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/PortGroupListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["PortGroupDTO"][];
        };
        PortGroupRepositoryLinkDTO: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            notes: string;
            portGroupId: string;
            portSlotId: string;
            relationType: string;
            repository?: components["schemas"]["GithubRepositoryDTO"];
            repositoryId: string;
            required: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        PortGroupRepositoryLinkInputDTO: {
            id?: string;
            notes?: string;
            portSlotId?: string;
            relationType?: string;
            repositoryId?: string;
            required?: boolean;
        };
        PortGroupUpdateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/PortGroupUpdateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["PortGroupUpdateDTO"][];
        };
        PortGroupUpdateDTO: {
            assetLinks: components["schemas"]["PortGroupAssetLinkInputDTO"][];
            environmentName: string;
            environmentOwner: string;
            hostId: string;
            id: string;
            notes: string;
            /** Format: int64 */
            portPrefix: number;
            repositoryLinks: components["schemas"]["PortGroupRepositoryLinkInputDTO"][];
            /** @enum {string} */
            runtimeMode: "dind" | "host";
            runtimeName: string;
            serviceIp: string;
            slots: components["schemas"]["PortSlotInputDTO"][];
            status: string;
            tags: string;
        };
        PortSlotDTO: {
            containerName: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            name: string;
            notes: string;
            /** Format: int64 */
            port: number;
            portGroupId: string;
            protocol: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PortSlotInputDTO: {
            containerName?: string;
            id?: string;
            kind?: string;
            name?: string;
            notes?: string;
            /** Format: int64 */
            port?: number;
            protocol?: string;
            status?: string;
        };
        ServiceGroupBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ServiceGroupBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ServiceGroupDTO"][];
        };
        ServiceGroupCreateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ServiceGroupCreateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ServiceGroupCreateDTO"][];
        };
        ServiceGroupCreateDTO: {
            description?: string;
            kind?: string;
            name: string;
            notes?: string;
            portGroups?: components["schemas"]["ServiceGroupPortGroupInputDTO"][];
            status?: string;
        };
        ServiceGroupDTO: {
            /** Format: date-time */
            createdAt: string;
            description: string;
            id: string;
            kind: string;
            name: string;
            notes: string;
            portGroups: components["schemas"]["ServiceGroupPortGroupDTO"][];
            status: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ServiceGroupListDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ServiceGroupListDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ServiceGroupDTO"][];
        };
        ServiceGroupPortGroupDTO: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            notes: string;
            portGroup?: components["schemas"]["PortGroupDTO"];
            portGroupId: string;
            role: string;
            serviceGroupId: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ServiceGroupPortGroupInputDTO: {
            id?: string;
            notes?: string;
            portGroupId?: string;
            role?: string;
        };
        ServiceGroupUpdateBatchDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/schemas/ServiceGroupUpdateBatchDTO.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ServiceGroupUpdateDTO"][];
        };
        ServiceGroupUpdateDTO: {
            description: string;
            id: string;
            kind: string;
            name: string;
            notes: string;
            portGroups: components["schemas"]["ServiceGroupPortGroupInputDTO"][];
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "console-list-dependency-assets": {
        parameters: {
            query?: {
                q?: string;
                assetKind?: string;
                assetType?: string;
                provider?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyAssetListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-update-dependency-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DependencyAssetUpdateBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyAssetBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-create-dependency-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DependencyAssetCreateBatchDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyAssetBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-delete-dependency-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIDsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-begin-github-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubConnectionStartDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-list-github-installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-sync-github-installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIDsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubInstallationBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-list-github-repositories": {
        parameters: {
            query?: {
                q?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubRepositoryListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-get-github-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GithubStatusDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-list-hosts": {
        parameters: {
            query?: {
                q?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-update-hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostUpdateBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-create-hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostCreateBatchDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-delete-hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIDsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-list-port-groups": {
        parameters: {
            query?: {
                q?: string;
                sort?: "port" | "environment" | "status" | "updated_desc";
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortGroupListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-update-port-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortGroupUpdateBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortGroupBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-create-port-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortGroupCreateBatchDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortGroupBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-delete-port-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIDsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-export-port-groups": {
        parameters: {
            query?: {
                q?: string;
                sort?: "port" | "environment" | "status" | "updated_desc";
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-list-service-groups": {
        parameters: {
            query?: {
                q?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceGroupListDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-update-service-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceGroupUpdateBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceGroupBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-create-service-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceGroupCreateBatchDTO"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceGroupBatchDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "console-delete-service-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIDsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "complete-github-connection": {
        parameters: {
            query: {
                installation_id: number;
                setup_action?: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description See Other */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "receive-github-webhook": {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Delivery": string;
                "X-GitHub-Event": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
