name: deploy
run-name: deploy ${{ inputs.source-tag }}

on:
  workflow_call:
    inputs:
      source-tag: &source-tag-input
        description: Image tag to deploy.
        required: true
        type: string
    secrets:
      DEPLOY_SSH_PRIVATE:
        required: true

  workflow_dispatch:
    inputs:
      source-tag: *source-tag-input

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v1.2.5
        env:
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ inputs.source-tag }}
        with:
          host: ${{ vars.DEPLOY_SSH_HOST }}
          port: ${{ vars.DEPLOY_SSH_PORT }}
          username: ${{ vars.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE }}
          envs: DOCKER_IMAGE
          script: bash ${{ vars.DEPLOY_SCRIPT }}
